### ISSUE TITLE
Adding Clippy to CI checks

### ISSUE THREAD

**Issue by jw2476** [bgnerdclub/birb#15]
I think clippy should be added to our CI passes to ensure all code is as well written as possible, I'll dig out the command in a bit

**Comment by Alex-Programs** [comment]
It could also be worth auto-formatting, though I'm not sure if Github actions are able to modify repository state.

**Comment by jw2476** [comment]
I don't think I'd be comfortable letting GH actions makes commits and changes to code, however I can make the checks fail if rustfmt picks up any bad formatting
